export const GASTER_ENV = {
  SEND_DISABLED_THINKING: 'GASTER_CODE_SEND_DISABLED_THINKING',
  DESKTOP_SERVER_URL: 'GASTER_CODE_DESKTOP_SERVER_URL',
  COMPUTER_USE_HOST_BUNDLE_ID: 'GASTER_CODE_COMPUTER_USE_HOST_BUNDLE_ID',
  COMPUTER_USE_ENABLED: 'GASTER_CODE_COMPUTER_USE_ENABLED',
  DESKTOP_AWAIT_MCP: 'GASTER_CODE_DESKTOP_AWAIT_MCP',
  DESKTOP_AWAIT_MCP_TIMEOUT_MS: 'GASTER_CODE_DESKTOP_AWAIT_MCP_TIMEOUT_MS',
  SKIP_DOTENV: 'GASTER_CODE_SKIP_DOTENV',
  PREWARM_IDLE_TIMEOUT_MS: 'GASTER_CODE_PREWARM_IDLE_TIMEOUT_MS',
  TERMINAL_SHELL_ENV_DISABLED: 'GASTER_CODE_DISABLE_TERMINAL_SHELL_ENV',
} as const

export type GasterEnvKey = keyof typeof GASTER_ENV

export function getGasterEnvValue(
  key: GasterEnvKey,
  env: NodeJS.ProcessEnv = process.env,
): string | undefined {
  return env[GASTER_ENV[key]]
}

export function getGasterManagedEnvKeys(): string[] {
  return [GASTER_ENV.SEND_DISABLED_THINKING]
}
